name: mimik
api:
  name: beam
  swagger: node_modules/swagger-mbeam/mbeam-api-swagger.yml
  controllerPath: ../src/controllers
  securityHandlerPath: ../src/handlers
  outputPath: ./build
package:
  imageName: beam
  imageIndexFilePath: ./build/index.js
  outputFolder: ./deploy
